# Generated by Django 5.0.7 on 2024-07-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultColumn',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
            ],
            options={
                'unique_together': {('id', 'course', 'credit')},
            },
        ),
    ]
