# Generated by Django 5.0.7 on 2024-07-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultcolumn',
            unique_together={('id', 'course')},
        ),
        migrations.AlterField(
            model_name='resultcolumn',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='resultcolumn',
            name='credit',
        ),
    ]
